[[HelloWorldGo]]
arch = "aarch64"
git-tree-sha1 = "a5f8161ca1ab2e94fedd3578586fe06d7906177c"
libc = "musl"
os = "linux"

    [[HelloWorldGo.download]]
    sha256 = "9b66d6b02a370d0170a8c217a872cd1f3d53de267d4e63c22a40b49f04367f8a"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldGo_jll.jl/releases/download/HelloWorldGo-v1.0.4+0/HelloWorldGo.v1.0.4.aarch64-linux-musl.tar.gz"
[[HelloWorldGo]]
arch = "i686"
git-tree-sha1 = "ea8ea92ecd57aa602d254ca6c637309642202768"
os = "windows"

    [[HelloWorldGo.download]]
    sha256 = "5c96a327fc6f0dc71d533373bc6cc6719a1e477c72319b800f29abf1b1e7d812"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldGo_jll.jl/releases/download/HelloWorldGo-v1.0.4+0/HelloWorldGo.v1.0.4.i686-w64-mingw32.tar.gz"
[[HelloWorldGo]]
arch = "x86_64"
git-tree-sha1 = "53e88bee931ba76075c8a2c4afc79a7a4ac16bb8"
libc = "musl"
os = "linux"

    [[HelloWorldGo.download]]
    sha256 = "858fbbce4a051d06baa0a4528921bd689f2bcfcc632dd1086e53677010fbf458"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldGo_jll.jl/releases/download/HelloWorldGo-v1.0.4+0/HelloWorldGo.v1.0.4.x86_64-linux-musl.tar.gz"
[[HelloWorldGo]]
arch = "i686"
git-tree-sha1 = "95be92025c80b9f843c6e867364d4f5dc97ca43e"
libc = "glibc"
os = "linux"

    [[HelloWorldGo.download]]
    sha256 = "c22f8525feaf488c37abd5c53c046871edee050eaffc8eadedd6168e09bbeb6c"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldGo_jll.jl/releases/download/HelloWorldGo-v1.0.4+0/HelloWorldGo.v1.0.4.i686-linux-gnu.tar.gz"
[[HelloWorldGo]]
arch = "armv7l"
git-tree-sha1 = "049660263a87c742dcde64228b1653c4cdff67d1"
libc = "glibc"
os = "linux"

    [[HelloWorldGo.download]]
    sha256 = "c17e83de772a02becfe74546e24754fb41e1130456da0bf07b0cac13595de7ce"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldGo_jll.jl/releases/download/HelloWorldGo-v1.0.4+0/HelloWorldGo.v1.0.4.armv7l-linux-gnueabihf.tar.gz"
[[HelloWorldGo]]
arch = "aarch64"
git-tree-sha1 = "1a0e6aa225671cde262e5d36a972b26df3b1e031"
libc = "glibc"
os = "linux"

    [[HelloWorldGo.download]]
    sha256 = "833026bd21dc3c714f58ff2caba71c7ed234d72fde7705c06df3c89ca34a1fec"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldGo_jll.jl/releases/download/HelloWorldGo-v1.0.4+0/HelloWorldGo.v1.0.4.aarch64-linux-gnu.tar.gz"
[[HelloWorldGo]]
arch = "x86_64"
git-tree-sha1 = "73be07c66c7f426b0876942f7d53202ae945762c"
libc = "glibc"
os = "linux"

    [[HelloWorldGo.download]]
    sha256 = "516efc549a852f0cf7f82e2ac655d6db6a2a628ce4992265f19c76a9889eb360"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldGo_jll.jl/releases/download/HelloWorldGo-v1.0.4+0/HelloWorldGo.v1.0.4.x86_64-linux-gnu.tar.gz"
[[HelloWorldGo]]
arch = "powerpc64le"
git-tree-sha1 = "fbd916c27fb545b6b19c61702ae2682012934878"
libc = "glibc"
os = "linux"

    [[HelloWorldGo.download]]
    sha256 = "e439d07e0bd5e8270583dbf285c282a40d89e3db2a362da3015c44c753ec8a83"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldGo_jll.jl/releases/download/HelloWorldGo-v1.0.4+0/HelloWorldGo.v1.0.4.powerpc64le-linux-gnu.tar.gz"
[[HelloWorldGo]]
arch = "x86_64"
git-tree-sha1 = "bad5a07ab91c26c560e427fd04c886566b0e71cc"
os = "macos"

    [[HelloWorldGo.download]]
    sha256 = "81f13725c0882a20b0e9be164d46970eedc75b1f7f574a344a4e29dbe14bb2cf"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldGo_jll.jl/releases/download/HelloWorldGo-v1.0.4+0/HelloWorldGo.v1.0.4.x86_64-apple-darwin14.tar.gz"
[[HelloWorldGo]]
arch = "x86_64"
git-tree-sha1 = "4c735a9e5ac27d18b746cbc25bf09ec6e963abfe"
os = "freebsd"

    [[HelloWorldGo.download]]
    sha256 = "2f1c7bcb1c84c0c86e9ad528d8e2ac5dd673bd763b2e7d3f9b9f6d616c2c5dbe"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldGo_jll.jl/releases/download/HelloWorldGo-v1.0.4+0/HelloWorldGo.v1.0.4.x86_64-unknown-freebsd11.1.tar.gz"
[[HelloWorldGo]]
arch = "i686"
git-tree-sha1 = "16e9225f29a0cb54af3ba1325db121fe8a7f7876"
libc = "musl"
os = "linux"

    [[HelloWorldGo.download]]
    sha256 = "70c0e6324a5003baaca745581945998917baa5e80268e8b05c00ca57cb4215c2"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldGo_jll.jl/releases/download/HelloWorldGo-v1.0.4+0/HelloWorldGo.v1.0.4.i686-linux-musl.tar.gz"
[[HelloWorldGo]]
arch = "armv7l"
git-tree-sha1 = "383c8c2f13b8a506a219e61966cfae021f50aa3e"
libc = "musl"
os = "linux"

    [[HelloWorldGo.download]]
    sha256 = "cd0b2b5cbfb1677e839cf0c59493a47d8d7c214de3f88c6cb9827d3abbb4bdde"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldGo_jll.jl/releases/download/HelloWorldGo-v1.0.4+0/HelloWorldGo.v1.0.4.armv7l-linux-musleabihf.tar.gz"
[[HelloWorldGo]]
arch = "x86_64"
git-tree-sha1 = "4f2acd48b556d2675dfb688365f065b32b548a32"
os = "windows"

    [[HelloWorldGo.download]]
    sha256 = "d47a85ae86aaa47a7e8b37209a479f5d7859a8edce183cab6e006ca76b83f520"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldGo_jll.jl/releases/download/HelloWorldGo-v1.0.4+0/HelloWorldGo.v1.0.4.x86_64-w64-mingw32.tar.gz"
