[[HelloWorldGo]]
arch = "x86_64"
git-tree-sha1 = "a42c3c371070b9d8a1d24f031a957fb339f5c55e"
os = "macos"

    [[HelloWorldGo.download]]
    sha256 = "b067cfaca31d59dbb1e569b84cac68c8721bcd273d54682c921a50f46723398f"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldGo_jll.jl/releases/download/HelloWorldGo-v1.0.0+0/HelloWorldGo.v1.0.0.x86_64-apple-darwin14.tar.gz"
