[[HelloWorldGo]]
arch = "x86_64"
git-tree-sha1 = "a42c3c371070b9d8a1d24f031a957fb339f5c55e"
os = "macos"

    [[HelloWorldGo.download]]
    sha256 = "b067cfaca31d59dbb1e569b84cac68c8721bcd273d54682c921a50f46723398f"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldGo_jll.jl/releases/download/HelloWorldGo-v1.0.0+0/HelloWorldGo.v1.0.0.x86_64-apple-darwin14.tar.gz"
[[HelloWorldGo]]
arch = "x86_64"
git-tree-sha1 = "e387754a8a850c09798bd3f8befdea8459250fea"
libc = "musl"
os = "linux"

    [[HelloWorldGo.download]]
    sha256 = "cae61bd4e470e9c9e955f20220f45bd63bc8b4f1a0191b4702320ac12d47b816"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldGo_jll.jl/releases/download/HelloWorldGo-v1.0.0+0/HelloWorldGo.v1.0.0.x86_64-linux-musl.tar.gz"
[[HelloWorldGo]]
arch = "x86_64"
git-tree-sha1 = "90c570bdfa20932384507f3d6ab9c86a37fcb01f"
os = "freebsd"

    [[HelloWorldGo.download]]
    sha256 = "ae003062d7ec287b6863bf05c94755c7e1a32e37d91ff29657e74ddb8ec467d1"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldGo_jll.jl/releases/download/HelloWorldGo-v1.0.0+0/HelloWorldGo.v1.0.0.x86_64-unknown-freebsd11.1.tar.gz"
