[[HelloWorldGo]]
arch = "aarch64"
git-tree-sha1 = "21324a763ccd2492d7a7c71df663cf685975954b"
libc = "glibc"
os = "linux"

    [[HelloWorldGo.download]]
    sha256 = "8d50a551ca1c0a5e80268e7bd83605aa58c294d82a2d512c7efd626c606ca84d"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldGo_jll.jl/releases/download/HelloWorldGo-v1.0.0+0/HelloWorldGo.v1.0.0.aarch64-linux-gnu.tar.gz"
[[HelloWorldGo]]
arch = "aarch64"
git-tree-sha1 = "6632488533a5150966f8ef3606113d24b5ede4d0"
libc = "musl"
os = "linux"

    [[HelloWorldGo.download]]
    sha256 = "18cbd72eb7d4a3565ec87aa18107917bbd993cf42dd8e44ef30f25b5c2aefec4"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldGo_jll.jl/releases/download/HelloWorldGo-v1.0.0+0/HelloWorldGo.v1.0.0.aarch64-linux-musl.tar.gz"
[[HelloWorldGo]]
arch = "armv7l"
git-tree-sha1 = "ce59ab316af68232b91be50a93e95e76fd245769"
libc = "glibc"
os = "linux"

    [[HelloWorldGo.download]]
    sha256 = "5c540a60bbbda4f440e59635c0de5a13d409ef64488bdf39b7412edc94525d8a"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldGo_jll.jl/releases/download/HelloWorldGo-v1.0.0+0/HelloWorldGo.v1.0.0.arm-linux-gnueabihf.tar.gz"
[[HelloWorldGo]]
arch = "armv7l"
git-tree-sha1 = "79670aff5e40b3bc9f609ccc93bcecc1c96c6936"
libc = "musl"
os = "linux"

    [[HelloWorldGo.download]]
    sha256 = "8c74ab0cca2015195e7f8d3f3be4b114e02900cc2d02d5cad1fa5a3d76fda4b3"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldGo_jll.jl/releases/download/HelloWorldGo-v1.0.0+0/HelloWorldGo.v1.0.0.arm-linux-musleabihf.tar.gz"
[[HelloWorldGo]]
arch = "i686"
git-tree-sha1 = "6fbeeefc68d649656b44260c2d33f76a5e5ddcec"
libc = "glibc"
os = "linux"

    [[HelloWorldGo.download]]
    sha256 = "32efb27acddc54338a2cb2f1cde61323af40a662a4134b63a6914a7a5776db68"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldGo_jll.jl/releases/download/HelloWorldGo-v1.0.0+0/HelloWorldGo.v1.0.0.i686-linux-gnu.tar.gz"
